### ISSUE TITLE
Adding an image doesn't seem to work

### ISSUE THREAD

**Issue by frithnanth** [p6-pdf/PDF-API6#8]
I tried run this using different images:
```perl6
use PDF::API6;
use PDF::Content::Page :PageSizes;

sub MAIN($output, $file)
{
  my PDF::API6 $pdf .= new;
  $pdf.media-box = A4;
  my $page = $pdf.add-page;
  my $gfx = $page.gfx;
  my $image = $gfx.load-image($file);
  $gfx.do($image, 10, 20);
  $pdf.save-as($output);
}
```
but the resulting PDF doesn't show anything, just a blank page.
Is there something I'm overlooking?

**Comment by dwarring** [comment]
@frithnanth,
That looks right. I'm seeing an image at bottom left of the page. Image and PDF attached. 
![lightbulb](https://user-images.githubusercontent.com/274095/80144569-daf88c80-8602-11ea-882b-a5dac31db8cd.png)
[tst.pdf](https://github.com/p6-pdf/PDF-API6/files/4524954/tst.pdf)

Could you attach a sample image and output PDF?

**Comment by frithnanth** [comment]
@dwarring image and resulting PDF:
[test.pdf](https://github.com/p6-pdf/PDF-API6/files/4525024/test.pdf)
![IMG_20191125_142106](https://user-images.githubusercontent.com/3965144/80145903-3d28a180-85b1-11ea-9d7c-37b920b78c9a.jpg)

**Comment by dwarring** [comment]
Thanks,
I am also not seeing the image. Will investigate.

**Comment by dwarring** [comment]
@frithnanth 
Was a bug in PDF::Content::Image::JPEG, which was using $fh.read which truncates to 65536 bytes. Changed to $fh.slurp(:bin).

Fixed in PDF::Content 0.4.4 release (may take a little time to be indexed by zef).

**Comment by frithnanth** [comment]
I git-cloned and zef-installed the new version, which kind of works now.
The resulting PDF shows one part of the image (doesn't rescale it automatically) so I added a `$gfx.transform: :scale(.1);` line.
If I add that before the `$gfx.do` instruction then the image scales, but it's not rotated and the program outputs this warning:

> graphics operator operation 'cm' (ConcatMatrix) used outside of a 'q' ... 'Q' (Save .. Restore) graphics block

If I add that line after the `$gfx.do` instruction then the image is rotated, but it's not scaled and the program outputs the same warning.
Am I using those operators correctly?

**Comment by dwarring** [comment]
Hi @frithnanth,
Image needs to be scaled, or have the width or height set.

One way is to set either a width or height: `$gfx.do($image, 10, 20, :width(500));`
If only `:width` or `height` is given both the width and height are adjusted to scale the image.

When scaling, rotating or changes other graphics, they should be bracketed by `Save` and `Restore` to suppress the warning:
```
use PDF::API6;
use PDF::Content::Page :PageSizes;

sub postfix:<mm>(Numeric $v){ ($v * 2.83).round(1) };

sub MAIN($output, $file)
{
  my PDF::API6 $pdf .= new;
  $pdf.media-box = A4;
  my $page = $pdf.add-page;
  my $gfx = $page.gfx;
  my $image = $gfx.load-image($file);
  $gfx.Save;
  $gfx.transform: :scale(.1), :rotate(.1);
  $gfx.do($image, 10, 20);
  $gfx.Restore;
  $pdf.save-as($output);
}
```
Or alternatively use the `graphics` method, which adds the `Save`/`Restore` for you.
```
use PDF::API6;
use PDF::Content::Page :PageSizes;

sub postfix:<mm>(Numeric $v){ ($v * 2.83).round(1) };

sub MAIN($output, $file)
{
  my PDF::API6 $pdf .= new;
  $pdf.media-box = A4;
  my $page = $pdf.add-page;
  $page.graphics: -> $gfx {
      my $image = $gfx.load-image($file);
      $gfx.transform: :scale(.1), :rotate(.1);
      $gfx.do($image, 10, 20);
  }
  $pdf.save-as($output);
}

```

Note that `Save` `Restore` can be nested.
